spring:
  #应用名
  application:
    name: com.diaosichengxuyuan.spring.cloud.provider.order1
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/lhp_db?useUnicode=true&characterEncoding=utf8
    username: lhp_user
    password: ENC(xrIEAg+Ai0U5Sq/1LBqkkosm24nqPBcI)
    driver-class-name: com.mysql.jdbc.Driver

#服务端口
server:
  port: 10001

management:
  #管理端口
  port: 10011
  #安全检查
  security:
    enabled: true

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10003/eureka/
  instance:
    prefer-ip-address: true