#服务端口
server:
  port: 10000

management:
  #管理端口
  port: 10010
  #安全检查
  security:
    enabled: true

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lhp_db?useUnicode=true&characterEncoding=utf8
    username: lhp_user
    password: ENC(xrIEAg+Ai0U5Sq/1LBqkkosm24nqPBcI)
    driver-class-name: com.mysql.jdbc.Driver