spring:
  #应用名
  application:
    name: com.diaosichengxuyuan.spring.cloud.config.server
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/lhp_db?useUnicode=true&characterEncoding=utf8
    username: lhp_user
    password: ENC(xrIEAg+Ai0U5Sq/1LBqkkosm24nqPBcI)
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diaosichengxuyuan/spring
          username: 用户名
          password: 密码

#服务端口
server:
  port: 10005

management:
  #管理端口
  port: 10015
  #安全检查
  security:
    enabled: true